### ISSUE TITLE
Error on running `src/qdmr_parser/test.py`

### ISSUE THREAD

**Issue by nooralahzadeh** [tomerwolgithub/question-decomposition-to-sql#4]
Having the following error on running `src/qdmr_parser/test.py` :
```
Traceback (most recent call last):
  File "src/qdmr_parser/test.py", line 78, in <module>
    model = T5FineTuner.load_from_checkpoint(args.checkpoint_path)
  File "/home/ubuntu/anaconda3/envs/qdmr_parser_env/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 157, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "/home/ubuntu/anaconda3/envs/qdmr_parser_env/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 199, in _load_model_state
    model = cls(**_cls_kwargs)
  File "/home/ubuntu/question-decomposition-to-sql/src/qdmr_parser/model.py", line 32, in __init__
    self.model = T5ForConditionalGeneration.from_pretrained(hparams.model_name_or_path)
AttributeError: 'dict' object has no attribute 'model_name_or_path'
```

**Comment by nooralahzadeh** [comment]
It seems to put `self.hparams` instead or `hparams` solves the issue in the following line of `model.py`
https://github.com/tomerwolgithub/question-decomposition-to-sql/blob/2d939661cf6b4043da8f65d0a0c7d3a17b7b6946/src/qdmr_parser/model.py#L32
